export const LEVEL_TEMPLATES = {
  1: [
    'def reparer_systeme(a, b):',
    '    # [MKARP] Boot sequence: réparation du cœur de calcul',
    '    # MISSION : Retourner la somme de a et b',
    "    # Indice 1 : en Python, l'addition c'est +",
    '    # Indice 2 : return a + b',
    '    return ',
    '',
  ].join('\n'),
  2: [
    'def assembler_code(partie_A, partie_B):',
    '    # [Geek] Forge: assembler deux fragments comme un build CI',
    '    # MISSION : Retourner la concaténation de partie_A et partie_B',
    '    # Exemple : "CODE" + "123" -> "CODE123"',
    '    # Indice 1 : les chaînes se collent avec +',
    '    # Indice 2 : return partie_A + partie_B',
    '    return ',
    '',
  ].join('\n'),
  3: [
    'def alerte_surchauffe(temperature):',
    '    # [Geek] Réacteur en surchauffe (pense "critical hit")',
    '    # MISSION : Retourne True si temperature > 100, sinon False',
    '    # Indice 1 : une comparaison (>) renvoie déjà un booléen',
    '    # Indice 2 : return temperature > 100',
    '    return ',
    '',
  ].join('\n'),
  4: [
    'def compter_objets(inventaire):',
    "    # [Geek] Inventaire façon RPG: combien d'items dans le sac ? ",
    "    # MISSION : Retourner le nombre d'éléments dans la liste inventaire",
    '    # Indice 1 : len(...) donne la taille',
    '    # Indice 2 : return len(inventaire)',
    '    return ',
    '',
  ].join('\n'),
  5: [
    'def total_energie(liste_batteries):',
    "    # [Geek] Barres d'énergie façon Metroid: total à afficher",
    '    # MISSION : Retourner la somme des nombres de liste_batteries',
    '    # Indice 1 : sum(...) additionne une liste de nombres',
    '    # Indice 2 : return sum(liste_batteries)',
    '    return ',
    '',
  ].join('\n'),
  6: [
    'def activer_bouclier(energie):',
    '    # [Geek] Protocole 42: bouclier ONLINE si énergie suffisante',
    '    # MISSION : Retourne True si energie >= 42, sinon False',
    '    # Indice 1 : >= compare deux nombres',
    '    # Indice 2 : return energie >= 42',
    '    return ',
    '',
  ].join('\n'),
  7: [
    'def verifier_konami(sequence):',
    '    # [Geek] Konami Code: UP UP DOWN DOWN LEFT RIGHT LEFT RIGHT B A',
    '    # MISSION : Retourne True si sequence est EXACTEMENT ce code, sinon False',
    '    # Indice 1 : compare la liste à une liste "attendue"',
    '    # Indice 2 : return sequence == ["UP", ...]',
    '    return ',
    '',
  ].join('\n'),
  8: [
    'def choisir_arme(cote):',
    "    # [Geek] Choix d'arme: jedi/sith/neutral",
    '    # MISSION :',
    '    # - si cote == "jedi" -> "sabre_bleu"',
    '    # - si cote == "sith" -> "sabre_rouge"',
    '    # - sinon -> "blaster"',
    '    # Indice 1 : if / elif / else',
    '    return ',
    '',
  ].join('\n'),
  9: [
    'def meilleur_score(scores):',
    '    # [Geek] Leaderboard arcade: extraire le meilleur score',
    '    # MISSION : Retourner le maximum de la liste scores',
    '    # Si la liste est vide, retourne 0',
    '    # Indice 1 : max(...) donne le plus grand',
    '    # Indice 2 : pense au cas []',
    '    return ',
    '',
  ].join('\n'),
  10: [
    'def normaliser_code_acces(code):',
    "    # [Geek] SAS d'accès façon vaisseau: on nettoie le badge",
    '    # MISSION : Retourne code en MAJUSCULES, sans espaces avant/après',
    '    # Exemple : "  mkArp-10  " -> "MKARP-10"',
    '    # Indice 1 : strip() enlève les espaces autour',
    '    # Indice 2 : upper() met en majuscules',
    '    return ',
    '',
  ].join('\n'),
};

export const LEVEL_BRIEFING = {
  1: {
    title: 'Niveau 01 — Boot (Amateur)',
    text: "Tu es l'apprenti opérateur. Le cœur de calcul refuse de démarrer. Patch minimal requis avant T-10:00.",
  },
  2: {
    title: 'Niveau 02 — Build CI',
    text: 'Le pipeline est fragmenté. Assemble les modules avant que le système ne coupe la lumière (référence: build qui casse).',
  },
  3: {
    title: 'Niveau 03 — Surchauffe',
    text: 'Le réacteur atteint la zone rouge. Si ça dépasse le seuil, alerte immédiate (mode critical).',
  },
  4: {
    title: 'Niveau 04 — Inventaire RPG',
    text: 'Le sas réclame un inventaire propre. Compte les objets, sinon accès refusé.',
  },
  5: {
    title: 'Niveau 05 — Énergie',
    text: "Les batteries sont dispersées. Additionne l'énergie totale pour alimenter le système de survie.",
  },
  6: {
    title: 'Niveau 06 — Protocole 42',
    text: "Le bouclier doit être activé avant l'impact. Seuil de sécurité: 42 (parce que 42).",
  },
  7: {
    title: 'Niveau 07 — Konami',
    text: "Un ancien module accepte un code secret. S'il est exact, tu déverrouilles une voie express.",
  },
  8: {
    title: 'Niveau 08 — Armurerie',
    text: 'Choisis l\'arme selon ton alignement. Si tu hésites, prends le blaster.',
  },
  9: {
    title: 'Niveau 09 — Leaderboard',
    text: 'Le tableau des scores décide de la priorité des processus. Il faut le meilleur score (et gérer le vide).',
  },
  10: {
    title: 'Niveau 10 — SAS final',
    text: 'Dernier verrou: badge propre, sans espaces et en MAJUSCULES. Une fois validé, accès ROOT.',
  },
};
